(function(d){d.widget("mobile.arrowlist",{options:{theme:!1,clickEvent:"vclick"},_create:function(){var a=this,c=d.extend(this.options,this.element.jqmData("options")),e={elem:this.element,header:this.element.prepend('<h3 class="ui-bar-a" class="arrowlist-header"><div class="arrowlist-header-title"></div></h3>').children("h3").first(),list:this.element.children("span"),index:0};e.title=e.header.children("div").first();d.extend(a,{display:e});!1===c.theme&&(c.theme=d(this).closest("[data-theme]").attr("data-theme"),
"undefined"===typeof c.theme&&(c.theme="c"));a.display.leftArrow=d("<div>").buttonMarkup({icon:"arrow-l",theme:c.theme,iconpos:"notext",corners:!1,shadow:!0,inline:!0}).addClass("ui-corner-left").css({"float":"left",margin:"0px"}).prependTo(a.display.header);a.display.rightArrow=d("<div>").buttonMarkup({icon:"arrow-r",theme:c.theme,iconpos:"notext",corners:!1,shadow:!0,inline:!0}).addClass("ui-corner-right").css({"float":"right",margin:"0px"}).prependTo(a.display.header);d("<div>").css("clear","both").appendTo(a.display.header);
a.display.leftArrow.on(c.clickEvent,function(b){b.preventDefault();b=a.display.index;b=0>b-1?a.display.list.length-1:b-1;a._toggleTab(b);a.display.index=b});a.display.rightArrow.on(c.clickEvent,function(b){b.preventDefault();b=a.display.index;b=b+1>=a.display.list.length?0:b+1;a._toggleTab(b);a.display.index=b});a._toggleTab(a.display.index)},_toggleTab:function(a){var c=this.display.list;c.eq(this.display.index).children("div.arrowlist-content").hide();a=c.eq(a);a.children("div.arrowlist-content").show();
this.display.title.html(a.children("div.arrowlist-title").html())}})})(jQuery);

var MVC=function(h){function x(a,b){this.jqmPageID=a;this.controller=b;this.scope={};this.elements=this.view=null;this.repeatsAdded=!1}var u=this,v={},p={},w=["controller","model","click","repeat"],y=function(a,b){var e={};if(b)var d=b.length,c=b;else d=w.length,c=w;for(var l=0;l<d;l++){e[c[l]]={};for(var f=e[c[l]],q="mvc-"+c[l],g=a.find("["+q+"]"),k={},h=0,n=g.length;h<n;h++){var m=g[h].getAttribute(q);"radio"===g[h].getAttribute("type")&&(k.hasOwnProperty(m)?(m=m+"-"+k[m]++,g[h].setAttribute("mvc-model",
m)):k[m]=0);f[m]=g[h]}}return e},z=function(a){null==a.elements&&(a.elements=y(a.view,["click","model","repeat"]));var b=a.scope,e=a.elements.click,d;for(d in e)h(e[d]).click(function(){var c=this.getAttribute("mvc-click"),c=c.substring(0,c.length-2);if(b.hasOwnProperty(c)){var e=a.elements.model,f=a.scope,d;for(d in f){var g=e[d];if(g&&"function"!==typeof f[d])if("radio"!==g.getAttribute("type")){var k=s(g);f[d]=k}else if(k=s(g),!1!==k)f[d]=k;else for(g=0;23>g;g++)if(k=d+"-"+g,e.hasOwnProperty(k)){if(k=
s(e[k]),!1!==k){f[d]=k;break}}else break}b[c].call(this)}})},t=function(a,b){if(!a)return!1;if(/input/i.test(a.tagName)){var e=a.getAttribute("type");if("checkbox"===e)h(a).prop("checked",b).checkboxradio("refresh");else if("radio"===e)if(a.value===b)h(a).attr("checked","checked").checkboxradio("refresh");else return h(a).prop("checked",!1).checkboxradio("refresh"),!1;else a.value=b}else/select/i.test(a.tagName)?h(a).val(b).selectmenu("refresh"):a.innerHTML=a.innerHTML.replace(/(.*)(\{\{.+?\}\})(.*)/i,
"$1"+b+"$3");return!0},s=function(a){if(!a)return null;var b=a.getAttribute("type"),e=null;return e="checkbox"===b?h(a).prop("checked"):"radio"===b?h(a).prop("checked")?a.value:!1:null==b&&/select/i.test(a.tagName)?a.options[a.selectedIndex].value:a.value},r={},B=function(a){var b=a.elements.repeat;a=a.scope;for(var e in b){var d=b[e];if(a.hasOwnProperty(e)){var c=a[e],l=d.parentNode,f=/select/i.test(l.tagName),h=!0;if(f){var g=0,k=A();l.setAttribute("data-select-uid",k);r[k]={}}for(var p in c){var n=
c[p],m=d.cloneNode(!1);m.innerHTML=n.text;n.hasOwnProperty("value")&&(m.value=n.value);!f&&n.hasOwnProperty("action")?m.onclick=function(){n.action.call(this)}:f&&n.hasOwnProperty("action")&&(r[k][g.toString()]=n.action);h&&(f&&(l.parentNode.firstChild.innerHTML=n.text),h=!1);g++;l.appendChild(m)}f&&r.hasOwnProperty(k)&&(l.onchange=function(){var a=this.selectedIndex.toString(),b=this.getAttribute("data-select-uid");r[b].hasOwnProperty(a)&&r[b][a].call(this)});l.removeChild(d)}}},A=function(){function a(){return Math.floor(65536*
(1+Math.random())).toString(16).substring(1)}return function(){return a()+a()}}();return{controller:function(a,b,e){v[a]=new x(b,e);p.hasOwnProperty(b)||(p[b]=[]);p[b].push({name:a,ref:v[a]});return u},init:function(){for(var a in p)h(document).on("pagecreate",a,function(a){a=p[a.handleObj.selector];for(var e=0;e<a.length;e++){var d=a[e].ref,c=a[e].name;d.view=h('[mvc-controller="'+c+'"]');if(1==d.view.length)if(z(d),d.controller.call(this,d.scope),c=d,d=c.scope,!c.repeatsAdded&&c.elements.hasOwnProperty("repeat")&&
B(c),c.repeatsAdded=!0,c.elements.hasOwnProperty("model")){var c=c.elements.model,l=void 0;for(l in d){var f=c[l],q=d[l];if(f&&"function"!==typeof q)if("radio"!==f.getAttribute("type"))t(f,q);else for(t(f,q),f=0;23>f;f++){var g=l+"-"+f;if(c.hasOwnProperty(g)){if(t(c[g],q))break}else break}}}else console.log("updateView: No model elements found");else 1>d.view.length?console.log('Error: Could not find controller "'+c+"\"'s' view element."):console.log('Error: Controller "'+c+"\"'s' had more than one view element.")}});
return u}}}(jQuery);

MVC.controller("enterTripDataCtrl","#enterTripDataPage",function(a){a.date=generateJQMDateStr();a.businessTrip=!0;a.beginningOdometer=123;a.endingOdometer=321;a.favoriteTrip="2";a.favoriteTrips=[{value:"1",text:"First Text"},{value:"2",text:"Second Text"},{value:"3",text:"Add New Trip",action:function(){console.log("open modal window")}}];a.saveTrip=function(){console.log("date = "+a.date);console.log("business = "+a.businessTrip);console.log("beginningOdometer = "+a.beginningOdometer);console.log("endingOdometer = "+
a.endingOdometer);console.log("favoriteTrip = "+a.favoriteTrip);$.mobile.changePage("#tabsPage",{transition:"none",changeHash:!0})}});
MVC.controller("fuelCtrl","#tabsPage",function(a){a.date=generateJQMDateStr();a.odometer=729;a.fuelPrice=4.39;a.numGallons=11.23;a.totalCost=49.2997;a.gallonsText=12.58;a.mpgText=27.6;a.save=function(){console.log("date = "+a.date);console.log("odometer = "+a.odometer);console.log("fuelPrice = "+a.fuelPrice);console.log("numGallons = "+a.numGallons);console.log("totalCost = "+a.totalCost)};a.cancel=function(){console.log("cancel")}});
MVC.controller("reportsCtrl","#tabsPage",function(a){a.beginningOdometer=587.7;a.endingOdometer=1035.5;a.totalBusinessMileage=421.8;a.totalPersonalMileage=26;a.percentBusiness=94;a.percentPersonal=6;a.totalFuelPurchases=323.87;a.averageMPG=23.6});
MVC.controller("firstVisitCtrl","#firstVisitPage",function(a){a.measurementUnit="metric";a.employeeNumber=12345678;a.vehicleYear="2013";a.vehicleMake="Nissan";a.vehicleModel="Truck";a.licensePlate="JKY-7A8";a.state="TX";a.vinNumber="1234567890123456789";a.odometer=729;a.vehicleYears=[{text:"Vehicle Year",value:"0"},{text:"2014"},{text:"2013",action:function(){console.log("vehicle years 2013")}},{text:"2012",action:function(){console.log("vehicle years 2012")}}];a.vehicleMakes=[{text:"Vehicle Make",
value:"0"},{text:"Honda"},{text:"Lexus"},{text:"Nissan"},{text:"Mazda"},{text:"Volkswagen"}];a.states=[{text:"State",value:"0"},{text:"CA"},{text:"NY"},{text:"TX"}];a.submit=function(){console.log("measurementUnit = "+a.measurementUnit);console.log("employeeNumber = "+a.employeeNumber);console.log("vehicleYear = "+a.vehicleYear);console.log("state = "+a.state)};a.cancel=function(){console.log("cancel")}});MVC.init();
function generateJQMDateStr(){var a=new Date,b=a.getDate().toString(),c=(a.getMonth()+1).toString(),a=a.getFullYear().toString();1>=b.length&&(b="0"+b);1>=c.length&&(c="0"+c);return a+"-"+c+"-"+b};